# Jekyll and GitHub pages is difficult. 
# Copy the content between START and END, and customise the things flagged EDIT

# START COPY ME
# EDIT ME
# remote_theme: glasnt/myrtle@thinkspace
# repository: glasnt/repo_name
description       : "in which glasnt does the things"    # EDIT       
baseurl           : "/template"                             # EDIT

title_left         : "glasnt.com"
url                : "https://glasnt.com"
google_analytics   : G-265B4NHGG0
twitter_username   : "glasnt"     
postshare_enabled  : true
cardfolder: "/assets/cards"
permalink          : /:title/
markdown           : kramdown
highlighter        : rouge

navbar:
  - slug : /
    title: home
  - slug : /blog/about/
    title: about
  - slug: /talks/
    title: talks
  - slug: /writing/
    title: writing
  - slug: /blog/
    title: blog
  - slug: /blog/now/
    title: now
  - slug: /blog/archive/
    title: archive

# END COPY ME

# System settings start here, do not need to be copied.

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "myrtle.gemspec"
