# See also _data/default.yml, or override them here.

baseurl       : "/talks" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank

# Build settings
permalink   : /:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site
# Author settings
author:
  name     : "Katie McLaughlin"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate


exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "myrtle.gemspec"
